In [31]:
import numpy as np
import pandas as pd
cric_data = np.loadtxt("cric.tsv",skiprows=1)
cric_data.shape

(15, 4)

In [32]:
cric_data

array([[  0., 100.,  78., 342.],
       [  1.,  11.,  62., 191.],
       [  2.,   8.,  85., 252.],
       [  3.,  71.,  24., 307.],
       [  4., 104.,  17., 229.],
       [  5.,  18., 104., 246.],
       [  6.,   8.,  76., 226.],
       [  7.,  86.,  74., 288.],
       [  8.,  12.,  60., 216.],
       [  9.,  25.,  90., 304.],
       [ 10.,  56.,   6., 272.],
       [ 11.,  88.,  69., 302.],
       [ 12., 147.,  65., 312.],
       [ 13., 121., 146., 370.],
       [ 15.,  99., 110., 362.]])

In [33]:
sachin = cric_data[:,1]
sachin

array([100.,  11.,   8.,  71., 104.,  18.,   8.,  86.,  12.,  25.,  56.,
        88., 147., 121.,  99.])

In [34]:
rahul = cric_data[:,2]
rahul

array([ 78.,  62.,  85.,  24.,  17., 104.,  76.,  74.,  60.,  90.,   6.,
        69.,  65., 146., 110.])

In [35]:
dravid = cric_data[:,3]
dravid

array([342., 191., 252., 307., 229., 246., 226., 288., 216., 304., 272.,
       302., 312., 370., 362.])

In [41]:
print(np.mean(sachin))
print(np.mean(dravid))
print(np.mean(rahul))

63.6
281.26666666666665
71.06666666666666


In [43]:
print(np.median(sachin))
print(np.median(dravid))
print(np.median(rahul))

71.0
288.0
74.0
